# Generated by Django 2.2 on 2020-03-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_auto_20200306_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='temporary', upload_to='cinema_images/', verbose_name='پوستر'),
            preserve_default=False,
        ),
    ]
