# Generated by Django 2.2 on 2020-03-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_movie_images_field_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='image',
            field=models.ImageField(null=True, upload_to='movie_images/', verbose_name='تصویر'),
        ),
    ]
