# Generated by Django 2.2 on 2020-03-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_cinema_image_field_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='image',
            field=models.ImageField(null=True, upload_to='cinema_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movie_images/', verbose_name='پوستر'),
        ),
    ]
