# Generated by Django 2.2 on 2020-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_auto_20200306_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cinema_images/', verbose_name='تصویر'),
        ),
    ]
