# Generated by Django 2.2 on 2020-03-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_auto_20200319_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
